In [1]:
## Matrizes

matriz_A = [[1, 2, 3], [4, 5, 6]]

In [2]:
matriz_A

[[1, 2, 3], [4, 5, 6]]

In [3]:
matriz_A[0] # acessando a primeira linha

[1, 2, 3]

In [4]:
matriz_A[1] # acessando a segunda linha

[4, 5, 6]

In [6]:
matriz_A[0][1] # elemento da primeira linha e segunda coluna

2

In [7]:
import numpy as np

In [8]:
matriz_B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
print(matriz_B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
matriz_B[0]

array([1, 2, 3])

In [12]:
matriz_B[1]

array([4, 5, 6])

In [13]:
matriz_B[2][1]

8

In [ ]:
# transposição da matriz

In [14]:
matriz_transposta = matriz_B.transpose()
matriz_transposta

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
# adição de matrizes

matriz1 = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])
matriz2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
matriz1 + matriz2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [17]:
# multiplicação de matrizes

matriz1 = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])
matriz2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
np.dot(matriz1, matriz2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])