In [1]:
# Determinantes
import numpy as np

In [2]:
matriz = np.array([[1, 2, -3], [2, 1, 3], [2, 0, -1]])
print(matriz)

[[ 1  2 -3]
 [ 2  1  3]
 [ 2  0 -1]]


In [3]:
det = np.linalg.det(matriz)
det

20.99999999999999

In [8]:
# exemplo 2
A = np.random.randint(0, 10, size=(4, 4))
A

array([[6, 5, 4, 8],
       [9, 1, 3, 2],
       [2, 7, 6, 5],
       [2, 4, 5, 3]])

In [9]:
det_A = np.linalg.det(A)
det_A

-313.00000000000017

In [12]:
# Sistemas Lineares

matriz_A = np.array([[1, 2, 3], [2, 3, 3], [1, 2, 0]])
matriz_B = np.array([1, -3, 6])

In [14]:
matriz_A  # definindo matriz A

array([[1, 2, 3],
       [2, 3, 3],
       [1, 2, 0]])

In [15]:
matriz_B  # definindo vetor B

array([ 1, -3,  6])

In [16]:
matriz_inv_A = np.linalg.inv(matriz_A) # calculando a matriz inversa de A
matriz_inv_A

array([[-2.        ,  2.        , -1.        ],
       [ 1.        , -1.        ,  1.        ],
       [ 0.33333333, -0.        , -0.33333333]])

In [18]:
X = np.dot(matriz_inv_A, matriz_B) # resolvendo o sistema de equações lineares
X

array([-14.        ,  10.        ,  -1.66666667])