In [1]:
## Matriz transposta
import numpy as np

In [3]:
matriz = np.array([[1, 1, -3], [2, 1, 3], [2, 0, -1]])
matriz

array([[ 1,  1, -3],
       [ 2,  1,  3],
       [ 2,  0, -1]])

In [4]:
matriz.transpose()

array([[ 1,  2,  2],
       [ 1,  1,  0],
       [-3,  3, -1]])

In [5]:
matriz.T

array([[ 1,  2,  2],
       [ 1,  1,  0],
       [-3,  3, -1]])

In [7]:
# Matriz inversa
# condições: matriz original tem ser quadradra: 3x3
# determinante da matriz original tem quer ser diferente de zero

A = matriz
A

array([[ 1,  1, -3],
       [ 2,  1,  3],
       [ 2,  0, -1]])

In [8]:
# determinante
np.linalg.det(A)

13.0

In [10]:
# calculando a matriz inversa
A_inve = np.linalg.inv(A)
A_inve

array([[-0.07692308,  0.07692308,  0.46153846],
       [ 0.61538462,  0.38461538, -0.69230769],
       [-0.15384615,  0.15384615, -0.07692308]])

In [11]:
# multiplicando matriz original e inversa resulta na matriz identidade
np.dot(A,A_inve)

array([[ 1.00000000e+00, -5.55111512e-17,  5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00,  5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [12]:
# exemplo 2
B = np.array([[1, -1], [0, 2]])
B

array([[ 1, -1],
       [ 0,  2]])

In [13]:
np.linalg.det(B) # determinante

2.0

In [14]:
B_inv = np.linalg.inv(B) # matriz inversa
B_inv

array([[1. , 0.5],
       [0. , 0.5]])

In [15]:
np.dot(B, B_inv) # matriz identidade

array([[1., 0.],
       [0., 1.]])

In [16]:
# criando matriz identidade

I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])